language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: BerriJ
  server: https://test.pypi.org/legacy/
  password:
    secure: uoPPo1Q1oP0E29QD4AyMUYXzz0Fhs404mlFHpk3zoQvZxti0xmMwuIAPt9lI20A6Y6WKE28W9zVZhQ95fCI4IHOENjC12HRFWSbr6vmuNC44sxsbRA6RSSlWKuVpkplVDnd/OpnzQwqlq/ncaGJIfsEFWv8sujDZL50F8fE1udOdiYF3GlgYFwqfiaQPvxHvvEJn8NFmC9/yxMYAP6XM7CDrHkJfCZc8NI366OstY1cW6XWsDD99P+VsMFKxigRCtd/fvmtrNgvs/UgwQxvAo0VCaEL0EKjIwxPXIWAagjokdXs9NE4IoB98tQZmW+u6XRAqNQyz/aLSek+2TREhkTzcDYYnyOyDEKmQGQu1C8zEqP5kNT2NkZ4jGMCmSksmrYiUUA3FjVU++RPQd+6c3NUcwnaTvRIJ+ZRpQ+mlP/9eussyV0Gr3J9P5x3QDk2kThV7kuZ3JHi7iDigLZmrWnCfVDOEypGLZd+xZ6Vv/LOJwLf3XY8zbqNaCH2aO6Bb3XxzHneUpz4RmGK3dQ1+wvTs9IqtvO5vO4Wrmon6nfN7FGqTolwySAiT3WpqESdbR1pbiHMkxWhB8wYULRSaAyWWqKcEreMxWytYTVRpQ5Xn0aR2W0YbYw2WRwYCRiMMT+YmlUMvJ/h8goB3x+wBvTq6EiwtU0b4SmmkKqexjBo=
  on:
    repo: BerriJ/sstudentt
    python: 3.7
