language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: BerriJ
  server: https://test.pypi.org/legacy/
  password:
    secure: T5hNVwgyMFpoKAQ2q2aQh1S9P60jwxLDP8JufheoM0x2Q+uushWn03LAutpN3imc94qPjdruDmfLOeAltdtQLpnePqXc5TFvdJITNT5dEOzy8M1jdYWl7Tgmz+TsYMOTMLNcCjOg/AM/J64rDWm2EplheGfdmN9mL6bVasGEAnWhtbMex6uvYWDgGuLWLO95qfvV8OfRRJSpME2hgilE0Be3FAbyr/At1pQkz74bqECVdVX3iDBsyLj1ZUXWbkHoDvXqwqFlfuhyd5iNJwbPOF13tj7K5cVWEK1T4b/Qtq3dt3i5nOHppBfqup1B/dZBnc+bvVA72eVAEidZzidow2HJodddUhAUuAhICh1hQUeD+4l0tRwQicRUL/MfVVC+GWnkFtKtTVRD9dbCfDF5kd3ab+iswe9ETsEWyiNw+pJG30TgTn9XCcXSXcoXjvFyNZLwLzSR5CMSN52MWi1QGoHNOdfPaR0N0/C51zbJ3+7uQRxlogrJh3VRJtgqbm5J8vFtvCEerUqPRvM5yQSmd1yHiboGrIq1dbr6NPwKxTmRRubmNS3dr0I1EswjGp6zp7ZwWH3TJ74UIKQvf334TcFQBxOSxu+qyCJPEiabnX4WEx75v1+85C6zl643I1flrlWIz4Ajx5NbVavW3woCgE5ICZjLaTRgU8q4AQtvNDM=
  on:
    repo: BerriJ/sstudentt
    python: 3.7
