language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: wiAHY0smHnlBKutq8adxhE+u2G7oyM0IHqKSbzY8VCNqYF2YtCeK1IywBJOqFad7LqHnvjqulnLz67wJvwfHlFWJvYfSo57HQtyLHGfN1nwBMJu0yehivja1snqO2tEilm61+fAKoc5sYPSG3SpevdJ7+j6yDD+oIEYOvKyaxU8mSZt7APicMRgKFjNVAzMcH/uCsKSEQJb0EKQj8ilO8b/K6tU7/4bdRBrSopttEaVbgH+6Z/y6FM/Kxyz0zx463GyOciIAezbIOUUslgWQ5coXDNJvZlTzZ8nuXg1ZgISojPdArZLOZk+0MnTJX/Kf3PzsW3A7DEus8dhgCEEtizv/WQZIwjawrHFiXbz3qW6FcvSc9n6/6P06ElrdF9dApMeaszMVqQLJbjb3t7xO6sXzBDv81Ob96XmnBhSx74s2St6zcO8zF5MkzYKZfqxLxDlwV8KpPgF2Jc0LDAQTDi3B/n1J88sh2ruPNGOiaJMZzDLbf7fgMCqCVKKsI/X9USLYmPhq5f31zAfDcOIbxrHGMz2JTICXf0WXE2wvohRNkHKESC17AN8Vy2ady2G3MQm/CiIvRDOjreWne1/s233Q8a1AMe85oXCV78hB2z17o6FQ/acLihB2qohE+V8Zh6q5SvzxhMmrJxc8fcFAgU/QlFj95QzRZtwTaKA+4J0=
  on:
    tags: true
    repo: BerriJ/sstudentt
    python: 3.7
